### ISSUE TITLE
DB-Migrations: Finalize leftover DB-Migrations

### ISSUE THREAD

**Issue by kulla** [serlo/documentation#4]
- [ ] Convert all revisions into edtr-io
- [ ] Convert also license texts
- [x] https://github.com/serlo/db-migrations/issues/3 
- [ ] Delete old tables: `metadata`, `metadata_key`, `session`, `ad` (and related), `permission`, `role_inheritance`, `navigation_*`, `license`, `attachment_*`, `related_content` (and related ones), `url_alias`, `blog_post`, `user_field`, `comment_vote`, `context` (and related ones)

**Comment by kulla** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [DB-Migrations: Keine Markdown-Revisionen mehr in der DB + Update auf das neue Tabellenplugin (Blocker für "Formeln und Links in Kommentaren")](https://trello.com/c/9qL9sQti/83-db-migrations-keine-markdown-revisionen-mehr-in-der-db-update-auf-das-neue-tabellenplugin-blocker-f%C3%BCr-formeln-und-links-in-komme)

**Comment by CodingDive** [comment]
We should also think about having a somewhat consistent naming schema for foreign keys. Here I had no idea that `repository_id` points to `entity` until I checked the relationships. It would be much better to use for example `entity_id`  

![image](https://github.com/serlo/documentation/assets/28842311/328bffcc-9004-46f5-8178-9f6f905c36d4)

**Comment by CodingDive** [comment]
We should also use this migration to get rid of old tables like `metadata` and `metadata_key`. 

Maybe there are also some other tables that are no longer being used.

**Comment by kulla** [comment]
All done in other PRs...
